name: udemy_fltr
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  age: ^0.0.1
  animated_text_kit: ^4.2.2
  flutter_app_name: ^0.1.1
  audioplayers: ^1.1.1
  rflutter_alert: ^2.0.4



  google_fonts: ^3.0.1
  url_launcher: ^6.1.7
  lottie: ^2.0.0



flutter_app_name:
  name: "Abbas Bhatti"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/
    - assets/images/
    - assets/music/sound/assets_note1.wav
    - assets/music/sound/assets_note2.wav
    - assets/music/sound/assets_note3.wav
    - assets/music/sound/assets_note4.wav
    - assets/music/sound/assets_note5.wav
    - assets/music/sound/assets_note6.wav
    - assets/music/sound/assets_note7.wav




  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
